# Generated by Django 3.1.2 on 2021-05-04 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='data',
            new_name='date',
        ),
    ]
