# Generated by Django 3.1.2 on 2021-06-16 15:01

import django.contrib.postgres.fields
from django.db import migrations, models
import games.chessSettings


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whitechessboard',
            name='bishops',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), default=games.chessSettings.ArrayFunc.get_white_bishops, max_length=2, size=None),
        ),
    ]
