# Generated by Django 3.1.2 on 2021-05-16 13:50

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import games.chessPos


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0003_auto_20210504_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='who_has_turn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hasTurn', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='WhiteChessBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pawns', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), max_length=2, size=None), default=games.chessPos.get_white_pawns, max_length=8, size=None)),
                ('knights', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), max_length=2, size=None), default=games.chessPos.get_white_knights, max_length=2, size=None)),
                ('queen', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), default=games.chessPos.get_white_queen, max_length=2, size=None)),
                ('bishops', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), max_length=2, size=None), default=games.chessPos.get_black_bishops, max_length=2, size=None)),
                ('rooks', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), max_length=2, size=None), default=games.chessPos.get_white_rooks, max_length=2, size=None)),
                ('king', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), default=games.chessPos.get_white_king, max_length=2, size=None)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='white_chess_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BlackChessBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pawns', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), max_length=2, size=None), default=games.chessPos.get_black_pawns, max_length=8, size=None)),
                ('knights', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), max_length=2, size=None), default=games.chessPos.get_black_knights, max_length=2, size=None)),
                ('queen', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), default=games.chessPos.get_black_queen, max_length=2, size=None)),
                ('bishops', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), max_length=2, size=None), default=games.chessPos.get_black_bishops, max_length=2, size=None)),
                ('rooks', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), max_length=2, size=None), default=games.chessPos.get_black_rooks, max_length=2, size=None)),
                ('king', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), default=games.chessPos.get_black_king, max_length=2, size=None)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='black_chess_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='blackChessBoard',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='black_chess', to='games.blackchessboard'),
        ),
        migrations.AddField(
            model_name='game',
            name='whiteChessBoard',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='white_chess', to='games.whitechessboard'),
        ),
    ]
